/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { Html, useGLTF } from "@react-three/drei";

export function Notebook3({ video, ...props }) {
  const { nodes, materials } = useGLTF("/models/Notebook3.glb");

  return (
    <group
      {...props}
      dispose={null}
      scale={[1.6, 1.6, 1.6]}
      position={[2, -7, 0]}
    >
      <pointLight
        intensity={24351}
        decay={2}
        color="#ffffff"
        position={[0.006, 17.936, -0.006]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={24351.413}
        decay={2}
        color="#ffffff"
        position={[0.006, 17.936, -20.006]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <pointLight
        intensity={24351.413}
        decay={2}
        color="#ffffff"
        position={[0.006, -17.936, -20.006]}
        rotation={[-Math.PI / 2, 0, 0]}
      />
      <group
        name="Notebook"
        position={[-1.046, 5.537, 2.187]}
        rotation={[0.266, 0, 0]}
      >
        <mesh
          name="Mesh001"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials.Notebook}
        />
        <mesh
          name="Mesh001_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials["Plastico negro"]}
        />
        <mesh
          name="Mesh001_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_2.geometry}
          material={materials["darkish grey plastic"]}
        />
        <mesh
          name="Mesh001_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_3.geometry}
          material={materials.metal}
        />
      </group>
      <group
        name="Pantalla"
        position={[-0.126, 15.831, -5.453]}
        rotation={[0.266, 0, 0]}
      >
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.Metal}
        />
        <mesh
          name="Cube009_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.Pantalla}
        >
          <Html
            transform
            occlude="blending"
            position={[-0, -0.4, 0.33]}
            rotation={[-0.27, 0, 0]}
            // scale={[1.21, 1.31, 1.21]}
            className="w-[945px] h-[625px] bg-black flex items-start"
          >
            <video
              src={video}
              controls
              autoPlay
              muted
              playsInline
              loop
              className="w-full h-auto"
            ></video>
          </Html>
        </mesh>
        <mesh
          name="Cube009_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials.Camara}
        />
      </group>
      <mesh
        name="Teclado"
        castShadow
        receiveShadow
        geometry={nodes.Teclado.geometry}
        material={materials.Teclado}
        position={[2.222, 6.626, -0.766]}
        rotation={[0.266, 0, 0]}
        scale={[1.136, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/models/Notebook3.glb");
