/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { Html, useGLTF } from "@react-three/drei";

export function Notebook4({ video, ...props }) {
  const { nodes, materials } = useGLTF("/models/Notebook4.glb");
  return (
    <group
      {...props}
      dispose={null}
      scale={[1.6, 1.6, 1.6]}
      position={[2, -7, 0]}
    >
      <pointLight
        name="Point"
        intensity={53514.131}
        decay={2}
        position={[-0.127, 32.029, 2.891]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={3.297}
      />
      <pointLight
        name="Point001"
        intensity={23514.131}
        decay={2}
        position={[-0.127, -15.235, -5.184]}
        rotation={[-2.256, 0, 0]}
        scale={3.297}
      />
      <pointLight
        name="Point002"
        intensity={23514.131}
        decay={2}
        position={[-0.127, 12.615, -23.813]}
        rotation={[-2.256, 0, 0]}
        scale={3.297}
      />
      <group
        name="Notebook"
        position={[-1.046, 5.537, 2.187]}
        rotation={[0.266, 0, 0]}
      >
        <mesh
          name="Mesh001"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001.geometry}
          material={materials.Notebook}
        />
        <mesh
          name="Mesh001_1"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_1.geometry}
          material={materials["Plastico negro"]}
        />
        <mesh
          name="Mesh001_2"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_2.geometry}
          material={materials["darkish grey plastic"]}
        />
        <mesh
          name="Mesh001_3"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_3.geometry}
          material={materials.metal}
        />
        <mesh
          name="Mesh001_4"
          castShadow
          receiveShadow
          geometry={nodes.Mesh001_4.geometry}
          material={materials.Material}
        />
      </group>
      <group
        name="Pantalla"
        position={[-0.126, 15.831, -5.453]}
        rotation={[0.266, 0, 0]}
      >
        <mesh
          name="Cube009"
          castShadow
          receiveShadow
          geometry={nodes.Cube009.geometry}
          material={materials.Metal}
        />
        <mesh
          name="Cube009_1"
          castShadow
          receiveShadow
          geometry={nodes.Cube009_1.geometry}
          material={materials.Pantalla}
        >
          <Html
            transform
            occlude="blending"
            position={[-0, 0.2, 0.33]}
            rotation={[-0.27, 0, 0]}
            sca
            // scale={[1.21, 1.31, 1.21]}
            className="w-[945px] h-[578px] bg-black flex items-start rounded-sm"
          >
            <video
              src={video}
              controls
              autoPlay
              muted
              playsInline
              loop
              className="w-full h-auto"
            ></video>
          </Html>
        </mesh>
        <mesh
          name="Cube009_2"
          castShadow
          receiveShadow
          geometry={nodes.Cube009_2.geometry}
          material={materials.Camara}
        />
      </group>
      <mesh
        name="Teclado"
        castShadow
        receiveShadow
        geometry={nodes.Teclado.geometry}
        material={materials.Teclado}
        position={[2.222, 6.626, -0.766]}
        rotation={[0.266, 0, 0]}
        scale={[1.136, 1, 1]}
      />
    </group>
  );
}

useGLTF.preload("/models/Notebook4.glb");
